### PR TITLE
#670 - Gene Symbol support dash and underscore

### PR DESCRIPTION
**Pull request by davmlaw**
For issue #670 - some HGNC symbols have dashes/underscores

### CODE REVIEW

**Comment by reece** [comment]
I think this is fine. However, would you please also consider and comment on the following alternative?

```
>>> import parsley
>>> g = parsley.makeGrammar("gene_symbol = <letter (letterOrDigit | ('-'|'_') ~~letterOrDigit)+>", {})
>>> def parseable(g, s):
...     try:
...         g(s).gene_symbol()
...         return True
...     except parsley.ParseError:
...         return False
... 
>>> for s in "ABC123 ABC_123 ABC-123 ABC__123    _ABC123 ABC123_ ABC/123".split():
...     print(f"{s}: {parseable(g,s)}")
... 
ABC123: True
ABC_123: True
ABC-123: True
ABC__123: False
_ABC123: False
ABC123_: False
ABC/123: False
```

The essential newness here is that the -_ requires a positive lookahead for a letter or digit, so therefore can't end an expression

Whaddya think?

**Comment by davmlaw** [comment]
Thanks @reece I had tried to do that but couldn't work out how.

Checked and tests are good, so have applied your change and updated pull request

**Comment by reece** [comment]
@davmlaw The PR looks the same to me. It doesn't look like your grammar rule is updated and it still uses `validate_gene_symbol`. Did you push?

**Comment by davmlaw** [comment]
@reece - sorry branching issue on my end, I think it's good now

**Comment by davmlaw** [comment]
@reece - I've found an issue - it doesn't support matching a gene without a transcript if it has a dash - eg "SP2-DT:c.1G>T" fails

**Review by reece — APPROVED** [review]

**Pull request merged**
