### PR TITLE
Add python runner

### PR DESCRIPTION
**Pull request by Estefanos8080**

### CODE REVIEW

**Comment by Estefanos8080** [comment]
Alternate way of running hgvs: the user can either type hgvs on command line or compile this class to launch hgvs.

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.

**Comment by davmlaw** [comment]
Hi, I recommend this code not be merged.

As a helper class, it takes longer to invoke than the underlying code - and it swallows exceptions

As a script, it's redundant as it just invokes "hgvs-shell"

**Comment by reece** [comment]
I concur with @davmlaw and am going with his recommendation.

**Pull request closed without merging**
