### PR TITLE
modernize: Python version support, CI/CD, & build

### PR DESCRIPTION
**Pull request by dmyersturnbull**
- [x] Test and document Python 3.11 support. Also drop past-EOL 3.6 and 3.7.
- [x] Fix small issues in docs
- [ ] Re-enable CI: I noticed the Travis tests no longer run. (I'm guessing when they changed to .com.) Would GitHub Actions be ok for this? I can add a new test workflow.
- [ ] pre-commit? I found that having tools like black run on commit can clean up diffs. If the devs like the idea, I'll add it.
- [ ] replace [https://github.com/readthedocs/sphinx_rtd_theme](rtd_theme)? It's now poorly maintained, and [furo](https://github.com/pradyunsg/furo) may be a good replacement.

### CODE REVIEW

**Comment by korikuzma** [comment]
+1 for pre-commit. We use this in our repos and it's really nice.

**Comment by jsstevenson** [comment]
I really like Furo as well -- though given that biocommons.org is using Material for Mkdocs, maybe it'd be better to standardize biocommons docs around that?

**Comment by reece** [comment]
Hi @dmyersturnbull : Awesome. All of these are great directions. The only input I have is that I'd prefer to see these changes as independent PRs. There's simply no reason to bundle them and small PRs are much easier (and safer) to consider.

https://github.com/biocommons/biocommons.example is intended to be the upstream template for all repos to ensure consistency. A better approach to your laudable goals would be to add them, one-by-one, to the example repo so that we can distribute them to all of biocommons projects. (e.g., commit hooks, black, etc.).

Thanks!

**Review by reece — COMMENTED** [review]
Hi @dmyersturnbull : Awesome. All of these are great directions. The only input I have is that I'd prefer to see these changes as independent PRs. There's simply no reason to bundle them and small PRs are much easier (and safer) to consider.

https://github.com/biocommons/biocommons.example is intended to be the upstream template for all repos to ensure consistency. A better approach to your laudable goals would be to add them, one-by-one, to the example repo so that we can distribute them to all of biocommons projects. (e.g., commit hooks, black, etc.).

Thanks!

**Comment by reece** [comment]
> I really like Furo as well -- though given that biocommons.org is using Material for Mkdocs, maybe it'd be better to standardize biocommons docs around that?

Some docs are in sphinx. I've been using mkdocs for the boicommons.org web pages. IMO, sphinx stinks for web sites and mkdocs stinks for complex docs (like those in hgvs), so for the moment I'm okay with having both and using the better tool for the job.

**Comment by reece** [comment]
This issue was closed by stalebot. It has been reopened to give more time for community review.  See [biocommons coding guidelines](https://biocommons.org/contributing/coding-guidelines/) for stale issue and pull request policies.  This resurrection is expected to be a one-time event.

**Pull request closed without merging**
