### PR TITLE
#628: add support for SeqFetcher to use seqrepo-rest-service as data source

### PR DESCRIPTION
**Pull request by bmrobin**
https://github.com/biocommons/hgvs/issues/628

### CODE REVIEW

**Comment by bmrobin** [comment]
@andreasprlic fyi as well

**Comment by andreasprlic** [comment]
does this also need a seqrepo library upgrade?

**Comment by bmrobin** [comment]
> does this also need a seqrepo library upgrade?

pushed 👍

**Review by andreasprlic — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
